title: CC Data Analyst Portfolio
remote_theme: jekyll/minima
plugins:
- jekyll-remote-theme
markdown: kramdown
header_pages:
  - index.md
  - projects/Cyclistic/README.md
  - projects/FDD-OCR/README.md
  - projects/Curriculum/README.md
  - projects/House_Prices/README.md
  - projects/Titanic-Kaggle/README.md

minima:
  skin: dark
