title: Carlos Portfolio
theme: minima
plugins:
- jekyll-remote-theme
markdown: kramdown
header_pages:
  - index.md
  - projects/Curriculum/README.md
links:
  - title: "LinkedIn"
    url: "https://www.linkedin.com/in/your-profile/"

minima:
  skin: auto
