title: Carlos Candamil Data Analyst Portfolio
description: 📊 or what
theme: minima
plugins:
  - jekyll-relative-links
markdown: kramdown
header_pages:
  - projects/Cyclistic
  - projects/FDD-OCR
  - projects/Curriculum
  - projects/House_Prices
  - projects/Titanic-Kaggle
